#!/usr/bin/env bash
# katusaOS Dynamic MOTD Script

BOLD='\033[1m'
CYAN='\033[96m'
GREEN='\033[92m'
YELLOW='\033[93m'
RESET='\033[0m'

echo -e "${CYAN}${BOLD}katusaOS${RESET} - ${GREEN}★ Katusa Programming Club Dedicated Operating System ★${RESET}\n"

echo -e "Welcome to ${BOLD}katusaOS${RESET}! Type '${YELLOW}katusa doctor${RESET}' to verify your toolchains,"
echo -e "or '${YELLOW}katusa --help${RESET}' for developer cheat sheets & starter templates."
echo ""
